[build]
  command = "npm run build" # Perintah untuk membangun proyek Anda (sesuai package.json)
  publish = "dist"         # Direktori output setelah build (Vite defaultnya 'dist')

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200